tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
brew "ack"
brew "ansible"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "coreutils", args: ["with-default-names"]
brew "git"
brew "docker"
brew "findutils", args: ["with-default-names"]
brew "git-lfs"
brew "gnu-sed", args: ["with-default-names"]
brew "gnupg"
brew "grep"
brew "htop"
brew "iftop"
brew "imagemagick", args: ["with-webp"]
brew "irssi"
brew "lua"
brew "moreutils"
brew "mtr"
brew "nmap"
brew "openssh"
brew "p7zip"
brew "pigz"
brew "pv"
brew "python"
brew "python3"
brew "ranger"
brew "rename"
brew "rlwrap"
brew "screen"
brew "ssh-copy-id"
brew "stow"
brew "terraform"
brew "tmux"
brew "tree"
brew "vim", args: ["with-override-system-vi"]
brew "wget"
cask "alfred"
cask "deluge"
cask "discord"
cask "keybase"
cask "postman"
cask "slack"
cask "spectacle"
cask "spotify"
cask "steam"
cask "synergy"
cask "typora"
cask "virtualbox"
cask "visual-studio-code"
cask "font-consolas-for-powerline"
cask "font-sourcecodepro-nerd-font-mono"
